name: teacher_app
description: "Real-time Student Task Management App for Teachers"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  provider: ^6.0.5
  font_awesome_flutter: ^10.6.0
  fl_chart: ^0.60.0
  shared_preferences: ^2.2.2
  file_picker: ^5.3.3
  open_file: ^3.3.1
  intl: ^0.18.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true  # Keep this for localization if needed
  assets:
    - assets/